27 machinesubscriber
Semesterproject4/back-end pull request #102
Opened 2021-05-14 12:41 UTC by Lawst96

Closes #27 

## Description
Provide details about your Pull Request and what it adds, fixes or changes.

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes, if necessary.
- [ ] All tests pass (existing and potential new).
- [ ] Sonar check has passed
- [ ] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

2021-05-14 13:52 UTC, Kaszz commented on BrewMesModulesParent/common_repository/src/main/java/com/brewmes/common_repository/BatchRepository.java
> +    List<Batch> findByConnectionID(String connectionID);
Det ligner ikke den bliver brugt længere?

2021-05-14 13:52 UTC, Kaszz commented on BrewMesModulesParent/subscriber/pom.xml
> +            <version>1.0-SNAPSHOT</version>
```suggestion
            <version>${project.version}</version>
```

2021-05-14 13:53 UTC, Kaszz commented on BrewMesModulesParent/subscriber/pom.xml
> +            <version>1.0-SNAPSHOT</version>
```suggestion
            <version>${project.version}</version>
```

2021-05-14 13:53 UTC, Kaszz commented on BrewMesModulesParent/api/pom.xml
> +            <version>1.0-SNAPSHOT</version>
```suggestion
            <version>${project.version}</version>
```

2021-05-14 13:56 UTC, Wylardt approved these changes
Good job guys

2021-05-14 15:34 UTC, Kechr requested changes
Haven't reviewed tests yet, as I saw you made some changes that haven't been pushed yet.

2021-05-14 17:44 UTC, Kechr commented on BrewMesModulesParent/subscriber/src/test/java/com/brewmes/subscriber/MachineSubscriberTest.java
> +        subscriptionStub.latestMachineData = fakeData;
Are these used in this test?

2021-05-14 17:45 UTC, Kechr commented on BrewMesModulesParent/common/src/main/java/com/brewmes/common/util/MachineState.java
> +    }
This method needs to be tested.

2021-05-15 09:57 UTC, Kaszz approved these changes
Hvis den metode Kenneth nævner bliver testet er det👍🏼

2021-05-17 06:16 UTC, Teyson approved these changes

2021-05-17 07:10 UTC, Kechr approved these changes

2021-05-17 07:14 UTC, merged