Adds a service to publish to the WebSocket
Semesterproject4/back-end pull request #169
Opened 2021-05-24 18:58 UTC by dottore1

Closes #

## Description
Adds a SPI(ILiveDataService)
Adds a implementation of the SPI to publish a MachineData object to the WebSocket

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes, if necessary.
- [x] All tests pass (existing and potential new).
- [x] Sonar check has passed
- [x] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

2021-05-24 19:37 UTC, Kechr requested changes
![image](https://user-images.githubusercontent.com/55458479/119398711-37335180-bcd8-11eb-8d0d-599f6b1abbab.png)
Needs more coverage.

2021-05-24 21:20 UTC, Lawst96 commented
> Needs more coverage.

Testing that method would be difficult as it contains a `new` keyword. It's doable but would require a lot of resources to implement. It was let through the last time a pull request was made on this class for this reason. It only counts as a new uncovered line because the constructor of `Subscription` has changed to include the new `liveDataService`.

2021-05-25 06:19 UTC, Kechr approved these changes

2021-05-25 06:24 UTC, Kaszz approved these changes

2021-05-25 06:27 UTC, Teyson approved these changes

2021-05-25 06:30 UTC, Wylardt approved these changes

2021-05-25 06:55 UTC, merged