61 BatchGetterImpl
Semesterproject4/back-end pull request #79
Opened 2021-05-11 08:42 UTC by Teyson

Closes #61

## Description
Adds the BatchGetterImpl and tests + cleans up some code

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes, if necessary.
- [ ] All tests pass (existing and potential new).
- [ ] Sonar check has passed
- [ ] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

2021-05-11 10:58 UTC, Lawst96 approved these changes

2021-05-11 12:05 UTC, dottore1 approved these changes

2021-05-11 13:32 UTC, Wylardt approved these changes

2021-05-11 14:04 UTC, Kechr requested changes
Build fails.

2021-05-11 19:04 UTC, Kechr requested changes

2021-05-11 19:04 UTC, Kechr commented on BrewMesModulesParent/api/src/main/java/com/brewmes/api/BatchController.java
> +            return new ResponseEntity<>("Error: Batch now found", HttpStatus.NOT_FOUND);
```suggestion
            return new ResponseEntity<>("Error: Batch not found", HttpStatus.NOT_FOUND);
```

2021-05-12 06:26 UTC, Lawst96 approved these changes

2021-05-12 06:27 UTC, merged